# Generated by Django 5.0.6 on 2024-07-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_shipiingaddress_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='country',
        ),
    ]
